### ISSUE TITLE
when executing npx @artgenio/core, these errors happen!

### ISSUE THREAD

**Issue by theseusyang** [hisorange/artgen#4]
node-pre-gyp ERR! install request to https://github.com/kelektiv/node.bcrypt.js/releases/download/v5.0.1/bcrypt_lib-v5.0.1-napi-v3-darwin-x64-unknown.tar.gz failed, reason: read ETIMEDOUT 
Cannot find module 'dns/promises'
Require stack:
- /Users/theseusyang/.npm/_npx/1927/lib/node_modules/@artgenio/core/build/modules/http/lambda/dns-query.lambda.js
- /Users/theseusyang/.npm/_npx/1927/lib/node_modules/@artgenio/core/build/modules/http/http.module.js
- /Users/theseusyang/.npm/_npx/1927/lib/node_modules/@artgenio/core/build/app/app.module.js
- /Users/theseusyang/.npm/_npx/1927/lib/node_modules/@artgenio/core/build/main.js
- /Users/theseusyang/.npm/_npx/1927/lib/node_modules/@artgenio/core/bin/artgen
(node:1927) [FST_MODULE_DEP_FASTIFY-STATIC] FastifyWarning.fastify-static: fastify-static has been deprecated. Use @fastify/static@5.0.0 instead.
(Use `node --trace-warnings ...` to show where the warning was created)
(node:1927) [FST_MODULE_DEP_FASTIFY-FORMBODY] FastifyWarning.fastify-formbody: fastify-formbody has been deprecated. Use @fastify/formbody@6.0.0 instead.
(node:1927) [FST_MODULE_DEP_FASTIFY-SECURE-SESSION] FastifyWarning.fastify-secure-session: fastify-secure-session has been deprecated. Use @fastify/secure-session@4.0.0 instead.

**Comment by theseusyang** [comment]
upgrade node version to 16.14.0, this error is away.

**Comment by hisorange** [comment]
Yep, the minimum version is now 16.x there was some change in the database drivers.
